eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
   service-url:
      defalutZone: http//localhost:8762/eureka/
   instace:
       hostname: localhost
    
   microservice:
       Micro-Service-2:
          endpoints
             endpoint:
                uri: http://MICRO-SERVICE-2/helloworld
   
       Micro-Service:
          endpoints:
             endpoint:
                uri: http://MICRO-SERVICE/helloworldd
